name: Playwright and Cucumber Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: npx playwright test
    
    - name: Run Cucumber tests
      run: npm run test
    
    - name: Generate Allure report
      run: npm run test:allure
    
    - name: Upload Playwright results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Cucumber results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cucumber-results
        path: |
          test-results/
          allure-report/
        retention-days: 30
